/*
 * XPilot, a multiplayer gravity war game.  Copyright (C) 1991-2001 by
 *
 *      Bjørn Stabell
 *      Ken Ronny Schouten
 *      Bert Gijsbers
 *      Dick Balaska
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, see
 * <https://www.gnu.org/licenses/>.
 */
/* Options parsing code contributed by Ted Lemon <mellon@ncd.com> */

#include <cstdlib>
#include <cstdio>
#include <cstring>
#include <cerrno>

#include "option.h"

#include "contact.h"
#include "server.h"

#define SERVER
#include "xpconfig.h"
#include "serverconst.h"

#include "defaults.h"
#include "xperror.h"
#include "portability.h"
#include "checknames.h"
#include "tuner.h"
#include "walls.h"
#include "sched.h"
#include "move.h"

double friction;
double coriolisCosine, coriolisSine; /* cos and sin of cor. angle */
int roundsPlayed = 0;                /* # of rounds played sofar. */
extern char conf_logfile_string[];   /* Default name of log file */

double timeStep = 1.0; /* Game time step per frame */
double timePerFrame;   /* Real time elapsed per frame */
double ecmSizeFactor;  /* Factor for ecm size update */
struct options options;

/*
 * Two functions which can be used if an option does not have its own
 * function which should be called after the option value has been
 * changed during runtime.  The tuner_none function should be
 * specified when an option cannot be changed at all during runtime.
 * The tuner_dummy can be specified if it is OK to modify the option
 * during runtime and no follow up action is needed.
 */
void tuner_none(void) { ; }
void tuner_dummy(void) { ; }

static void Tune_robot_user_name(void)
{
    Fix_user_name(options.robotUserName);
}
static void Tune_robot_host_name(void)
{
    Fix_host_name(options.robotHostName);
}
static void Tune_tank_user_name(void)
{
    Fix_user_name(options.tankUserName);
}
static void Tune_tank_host_name(void)
{
    Fix_host_name(options.tankHostName);
}

static option_desc opts[] = {
    {"help",
     "help",
     "0",
     NULL,
     valVoid,
     tuner_none,
     "Print out this help message.\n",
     OPT_NONE},
    {"version",
     "version",
     "0",
     NULL,
     valVoid,
     tuner_none,
     "Print version information.\n",
     OPT_NONE},
    {"dump",
     "dump",
     "0",
     NULL,
     valVoid,
     tuner_none,
     "Print all options and their default values in defaultsfile format.\n",
     OPT_NONE},
    {"expand",
     "expand",
     "",
     &options.expandList,
     valList,
     tuner_none,
     "Expand a comma separated list of predefined settings.\n"
     "These settings can be defined in either the defaults file\n"
     "or in a map file using the \"define:\" operator.\n",
     OPT_COMMAND},
    {"gravity",
     "gravity",
     "-0.14",
     &options.gravity,
     valReal,
     Compute_gravity,
     "Gravity strength.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"shipMass",
     "shipMass",
     "20.0",
     &options.shipMass,
     valReal,
     tuner_shipmass,
     "Mass of fighters.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"ballMass",
     "ballMass",
     "50.0",
     &options.ballMass,
     valReal,
     tuner_ballmass,
     "Mass of balls.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"shotMass",
     "shotMass",
     "0.1",
     &options.shotMass,
     valReal,
     tuner_dummy,
     "Mass of bullets.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"shotSpeed",
     "shotSpeed",
     "21.0",
     &options.shotSpeed,
     valReal,
     tuner_dummy,
     "Maximum speed of bullets.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"shotLife",
     "shotLife",
     "60",
     &options.shotLife,
     valInt,
     tuner_dummy,
     "Life of bullets in ticks.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"fireRepeatRate",
     "fireRepeat",
     "2",
     &options.fireRepeatRate,
     valInt,
     tuner_dummy,
     "Number of frames per automatic fire (0=off).\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"maxRobots",
     "robots",
     "4",
     &options.maxRobots,
     valInt,
     tuner_maxrobots,
     "The maximum number of robots wanted.\n"
     "Adds robots if there are less than maxRobots players.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"minRobots",
     "minRobots",
     "-1",
     &options.minRobots,
     valInt,
     tuner_minrobots,
     "The minimum number of robots wanted.\n"
     "At least minRobots robots will be in the game, if there is room.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"robotFile",
     "robotFile",
     NULL,
     &options.robotFile,
     valString,
     tuner_none,
     "The file containing parameters for robot details.\n",
     OPT_COMMAND | OPT_DEFAULTS},
    {"robotsTalk",
     "robotsTalk",
     "false",
     &options.robotsTalk,
     valBool,
     tuner_dummy,
     "Do robots talk when they kill, die etc.?\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"robotsLeave",
     "robotsLeave",
     "true",
     &options.robotsLeave,
     valBool,
     tuner_dummy,
     "Do robots leave the game?\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"robotLeaveLife",
     "robotLeaveLife",
     "50",
     &options.robotLeaveLife,
     valInt,
     tuner_dummy,
     "Max life per robot (0=off).\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"robotLeaveScore",
     "robotLeaveScore",
     "-90",
     &options.robotLeaveScore,
     valInt,
     tuner_dummy,
     "Min score for robot to play (0=off).\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"robotLeaveRatio",
     "robotLeaveRatio",
     "-5",
     &options.robotLeaveRatio,
     valInt,
     tuner_dummy,
     "Min ratio for robot to play (0=off).\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"robotTeam",
     "robotTeam",
     "0",
     &options.robotTeam,
     valInt,
     tuner_dummy,
     "Team to use for robots.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"restrictRobots",
     "restrictRobots",
     "true",
     &options.restrictRobots,
     valBool,
     tuner_dummy,
     "Are robots restricted to their own team?\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"reserveRobotTeam",
     "reserveRobotTeam",
     "true",
     &options.reserveRobotTeam,
     valBool,
     tuner_dummy,
     "Is the robot team only for robots?\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"robotUserName",
     "robotUserName",
     "robot",
     &options.robotUserName,
     valString,
     Tune_robot_user_name,
     "What is the robots' apparent real name?\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"robotHostName",
     "robotHostName",
     "xpilot.org",
     &options.robotHostName,
     valString,
     Tune_robot_host_name,
     "What is the robots' apparent host name?\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"tankUserName",
     "tankUserName",
     "tank",
     &options.tankUserName,
     valString,
     Tune_tank_user_name,
     "What is the tanks' apparent real name?\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"tankHostName",
     "tankHostName",
     "tanks.org",
     &options.tankHostName,
     valString,
     Tune_tank_host_name,
     "What is the tanks' apparent host name?\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"tankScoreDecrement",
     "tankDecrement",
     "500",
     &options.tankScoreDecrement,
     valInt,
     tuner_dummy,
     "How much lower is the tank's score than the player's?\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"selfImmunity",
     "selfImmunity",
     "false",
     &options.selfImmunity,
     valBool,
     tuner_dummy,
     "Are players immune to their own weapons?\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"defaultShipShape",
     "defaultShipShape",
     "(NM:Default)(AU:Unknown)(SH: 15,0 -9,8 -9,-8)(MG: 15,0)(LG: 15,0)"
     "(RG: 15,0)(EN: -9,0)(LR: -9,8)(RR: -9,-8)(LL: -9,8)(RL: -9,-8)"
     "(MR: 15,0)",
     &options.defaultShipShape,
     valString,
     tuner_none,
     "What is the default ship shape for people who do not have a ship\n"
     "shape defined?",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"tankShipShape",
     "tankShipShape",
     "(NM:fueltank)(AU:John E. Norlin)"
     "(SH: 15,0 14,-5 9,-8 -5,-8 -3,-8 -3,0 "
     "2,0 2,2 -3,2 -3,6 5,6 5,8 -5,8 -5,-8 "
     "-9,-8 -14,-5 -15,0 -14,5 -9,8 9,8 14,5)"
     "(EN: -15,0)(MG: 15,0)",
     &options.tankShipShape,
     valString,
     tuner_none,
     "What is the ship shape used for tanks?",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"maxPlayerShots",
     "shots",
     "256",
     &options.maxPlayerShots,
     valInt,
     tuner_dummy,
     "Maximum number of shots visible at the same time per player.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"shotsGravity",
     "shotsGravity",
     "true",
     &options.shotsGravity,
     valBool,
     tuner_dummy,
     "Are shots affected by gravity.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"Log",
     "Log",
     "false",
     &options.Log,
     valBool,
     tuner_dummy,
     "Log major server events to log file?\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"idleRun",
     "rawMode",
     "false",
     &options.RawMode,
     valBool,
     tuner_dummy,
     "Do robots keep on playing even if all human players quit?\n",
     OPT_COMMAND | OPT_DEFAULTS | OPT_VISIBLE},
    {"noQuit",
     "noQuit",
     "false",
     &options.NoQuit,
     valBool,
     tuner_dummy,
     "Does the server wait for new human players to show up\n"
     "after all players have left.\n",
     OPT_COMMAND | OPT_DEFAULTS | OPT_VISIBLE},
    {"logRobots",
     "logRobots",
     "true",
     &options.logRobots,
     valBool,
     tuner_dummy,
     "Log the comings and goings of robots.\n",
     OPT_COMMAND | OPT_DEFAULTS | OPT_VISIBLE},
    {"mapWidth",
     "mapWidth",
     "100",
     &options.mapWidth,
     valInt,
     tuner_none,
     "Width of the world in blocks.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"mapHeight",
     "mapHeight",
     "100",
     &options.mapHeight,
     valInt,
     tuner_none,
     "Height of the world in blocks.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"mapFileName",
     "map",
     NULL,
     &options.mapFileName,
     valString,
     tuner_none,
     "The filename of the map to use.\n"
     "Or \"wild\" if you want a map by The Wild Map Generator.\n"
     "The geometry of a \"wild\" map is given by the -mapWidth\n"
     "and the -mapHeight options.\n",
     OPT_COMMAND | OPT_DEFAULTS},
    {"mapName",
     "mapName",
     "unknown",
     &options.mapName,
     valString,
     tuner_none,
     "The title of the map.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"mapAuthor",
     "mapAuthor",
     "anonymous",
     &options.mapAuthor,
     valString,
     tuner_none,
     "The name of the map author.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"contactPort",
     "port",
     "15345",
     &options.contactPort,
     valInt,
     tuner_none,
     "The server contact port number.\n",
     OPT_COMMAND | OPT_DEFAULTS | OPT_VISIBLE},
    {"serverHost",
     "serverHost",
     NULL,
     &options.serverHost,
     valString,
     tuner_none,
     "The server's fully qualified domain name (for multihomed hosts).\n",
     OPT_COMMAND | OPT_DEFAULTS | OPT_VISIBLE},
    {"mapData",
     "mapData",
     NULL,
     &options.mapData,
     valString,
     tuner_none,
     "The map's topology.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"greeting",
     "xpilotGreeting",
     NULL,
     &options.greeting,
     valString,
     tuner_dummy,
     "Short greeting string for players when they login to server.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"allowPlayerCrashes",
     "allowPlayerCrashes",
     "true",
     &options.allowPlayerCrashes,
     valBool,
     Set_world_rules,
     "Can players overrun other players?\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"allowPlayerBounces",
     "allowPlayerBounces",
     "true",
     &options.allowPlayerBounces,
     valBool,
     Set_world_rules,
     "Can players bounce with other players?\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"allowPlayerKilling",
     "killings",
     "true",
     &options.allowPlayerKilling,
     valBool,
     Set_world_rules,
     "Should players be allowed to kill one other?\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"allowShields",
     "shields",
     "true",
     &options.allowShields,
     valBool,
     tuner_allowshields,
     "Are shields allowed?\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"playerStartsShielded",
     "playerStartShielded",
     "true",
     &options.playerStartsShielded,
     valBool,
     tuner_playerstartsshielded,
     "Do players start with shields up?\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"shotsWallBounce",
     "shotsWallBounce",
     "false",
     &options.shotsWallBounce,
     valBool,
     Move_init,
     "Do shots bounce off walls?\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"ballsWallBounce",
     "ballsWallBounce",
     "true",
     &options.ballsWallBounce,
     valBool,
     Move_init,
     "Do balls bounce off walls?\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"ballCollisions",
     "ballCollisions",
     "false",
     &options.ballCollisions,
     valBool,
     tuner_dummy,
     "Can balls collide with other objects?\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"ballSparkCollisions",
     "ballSparkCollisions",
     "true",
     &options.ballSparkCollisions,
     valBool,
     tuner_dummy,
     "Can balls be blown around by exhaust? (Needs ballCollisions too)\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"minesWallBounce",
     "minesWallBounce",
     "false",
     &options.minesWallBounce,
     valBool,
     Move_init,
     "Do mines bounce off walls?\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"itemsWallBounce",
     "itemsWallBounce",
     "true",
     &options.itemsWallBounce,
     valBool,
     Move_init,
     "Do items bounce off walls?\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"missilesWallBounce",
     "missilesWallBounce",
     "false",
     &options.missilesWallBounce,
     valBool,
     Move_init,
     "Do missiles bounce off walls?\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"sparksWallBounce",
     "sparksWallBounce",
     "false",
     &options.sparksWallBounce,
     valBool,
     Move_init,
     "Do thrust spark particles bounce off walls to give reactive thrust?\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"debrisWallBounce",
     "debrisWallBounce",
     "false",
     &options.debrisWallBounce,
     valBool,
     Move_init,
     "Do explosion debris particles bounce off walls?\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"asteroidsWallBounce",
     "asteroidsWallBounce",
     "true",
     &options.asteroidsWallBounce,
     valBool,
     Move_init,
     "Do asteroids bounce off walls?\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"cloakedExhaust",
     "cloakedExhaust",
     "true",
     &options.cloakedExhaust,
     valBool,
     tuner_dummy,
     "Do engines of cloaked ships generate exhaust?\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    // TODO: Make some warning that this option is not supported, in the case that the map
    // specifies that this should be off.
    // {"cloakedShield",
    //  "cloakedShield",
    //  "true",
    //  &options.cloakedShield,
    //  valBool,
    //  tuner_dummy,
    //  "Can players use shields when cloaked?\n",
    //  OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"maxObjectWallBounceSpeed",
     "maxObjectBounceSpeed",
     "40",
     &options.maxObjectWallBounceSpeed,
     valReal,
     Move_init,
     "The maximum allowed speed for objects to bounce off walls.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"maxShieldedWallBounceSpeed",
     "maxShieldedBounceSpeed",
     "50",
     &options.maxShieldedWallBounceSpeed,
     valReal,
     Move_init,
     "The maximum allowed speed for a shielded player to bounce off walls.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"maxUnshieldedWallBounceSpeed",
     "maxUnshieldedBounceSpeed",
     "20",
     &options.maxUnshieldedWallBounceSpeed,
     valReal,
     Move_init,
     "Maximum allowed speed for an unshielded player to bounce off walls.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"maxShieldedPlayerWallBounceAngle",
     "maxShieldedBounceAngle",
     "90",
     &options.maxShieldedWallBounceAngle,
     valReal,
     Move_init,
     "Maximum allowed angle for a shielded player to bounce off walls.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"maxUnshieldedPlayerWallBounceAngle",
     "maxUnshieldedBounceAngle",
     "30",
     &options.maxUnshieldedWallBounceAngle,
     valReal,
     Move_init,
     "Maximum allowed angle for an unshielded player to bounce off walls.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"playerWallBounceBrakeFactor",
     "playerWallBrake",
     "0.89",
     &options.playerWallBrakeFactor,
     valReal,
     Move_init,
     "Factor to slow down players when they hit the wall (0 to 1).\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"objectWallBounceBrakeFactor",
     "objectWallBrake",
     "0.95",
     &options.objectWallBounceBrakeFactor,
     valReal,
     Move_init,
     "Factor to slow down objects when they hit the wall (0 to 1).\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"objectWallBounceLifeFactor",
     "objectWallBounceLifeFactor",
     "0.80",
     &options.objectWallBounceLifeFactor,
     valReal,
     Move_init,
     "Factor to reduce the life of objects after bouncing (0 to 1).\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"wallBounceFuelDrainMult",
     "wallBounceDrain",
     "1.0",
     &options.wallBounceFuelDrainMult,
     valReal,
     Move_init,
     "Multiplication factor for player wall bounce fuel cost.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"wallBounceDestroyItemProb",
     "wallBounceDestroyItemProb",
     "0.0",
     &options.wallBounceDestroyItemProb,
     valReal,
     Move_init,
     "The probability for each item a player owns to get destroyed\n"
     "when the player bounces against a wall.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"reportToMetaServer",
     "reportMeta",
     "true",
     &options.reportToMetaServer,
     valBool,
     tuner_none,
     "Keep the meta server informed about our game?\n",
     OPT_COMMAND | OPT_DEFAULTS | OPT_VISIBLE},
    {"searchDomainForXPilot",
     "searchDomainForXPilot",
     "false",
     &options.searchDomainForXPilot,
     valBool,
     tuner_none,
     "Search the local domain for the existence of xpilot.domain?\n",
     OPT_COMMAND | OPT_DEFAULTS | OPT_VISIBLE},
    {"denyHosts",
     "denyHosts",
     "",
     &options.denyHosts,
     valString,
     Set_deny_hosts,
     "List of network addresses of computers which are denied service.\n"
     "Each address may optionally be followed by a slash and a network mask.\n",
     OPT_COMMAND | OPT_DEFAULTS | OPT_VISIBLE},
    {"maxClientsPerIP",
     "maxPerIP",
     "2",
     &options.maxClientsPerIP,
     valInt,
     tuner_dummy,
     "Maximum number of clients per IP address that are allowed to connect.\n"
     "This prevents unfriendly players from occupying all the bases"
     ", effectively \"kicking\" paused players and denying other players to join.\n",
     OPT_COMMAND | OPT_DEFAULTS | OPT_VISIBLE},
    {"limitedVisibility",
     "limitedVisibility",
     "false",
     &options.limitedVisibility,
     valBool,
     Set_world_rules,
     "Should the players have a limited visibility?\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"minVisibilityDistance",
     "minVisibility",
     "0.0",
     &options.minVisibilityDistance,
     valReal,
     tuner_dummy,
     "Minimum block distance for limited visibility, 0 for default.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"maxVisibilityDistance",
     "maxVisibility",
     "0.0",
     &options.maxVisibilityDistance,
     valReal,
     tuner_dummy,
     "Maximum block distance for limited visibility, 0 for default.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"limitedLives",
     "limitedLives",
     "false",
     &options.limitedLives,
     valBool,
     tuner_none,
     "Should players have limited lives?\n"
     "See also worldLives.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"worldLives",
     "lives",
     "0",
     &options.worldLives,
     valInt,
     tuner_worldlives,
     "Number of lives each player has (no sense without limitedLives).\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"reset",
     "reset",
     "true",
     &options.endOfRoundReset,
     valBool,
     tuner_dummy,
     "Does the world reset when the end of round is reached?\n"
     "When true all mines, missiles, shots and explosions will be\n"
     "removed from the world and all players including the winner(s)\n"
     "will be transported back to their homebases.\n"
     "This option is only effective when limitedLives is turned on.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"resetOnHuman",
     "humanReset",
     "0",
     &options.resetOnHuman,
     valInt,
     tuner_dummy,
     "Normally, new players have to wait until a round is finished\n"
     "before they can start playing. With this option, the first N\n"
     "human players to enter will cause the round to be restarted.\n"
     "In other words, if this option is set to 0, nothing special\n"
     "happens and you have to wait as usual until the round ends (if\n"
     "there are rounds at all, otherwise this option doesn't do\n"
     "anything). If it is set to 1, the round is ended when the first\n"
     "human player enters. This is useful if the robots have already\n"
     "started a round and you don't want to wait for them to finish.\n"
     "If it is set to 2, this also happens for the second human player.\n"
     "This is useful when you got bored waiting for another player to\n"
     "show up and have started playing against the robots. When someone\n"
     "finally joins you, they won't have to wait for you to finish the\n"
     "round before they can play too. For higher numbers it works the\n"
     "same. So this option gives the last human player for whom the\n"
     "round is restarted. Anyone who enters after that does have to\n"
     "wait until the round is over.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"allowAlliances",
     "alliances",
     "true",
     &options.allowAlliances,
     valBool,
     tuner_allowalliances,
     "Are alliances between players allowed?\n"
     "Alliances are like teams, except they can be formed and dissolved\n"
     "at any time. Notably, teamImmunity works for\n"
     "alliances too. To manage alliances, use the '/ally' talk command:\n"
     "'/ally invite <player name>' to invite another player to join you.\n"
     "'/ally cancel' to cancel such an invitation.\n"
     "'/ally refuse <player name>' to decline an invitation from a player.\n"
     "'/ally refuse' to decline all the invitations you received.\n"
     "'/ally accept <player name>' to join the other player.\n"
     "'/ally accept' to accept all the invitations you received.\n"
     "'/ally leave' to leave the alliance you are currently in.\n"
     "'/ally list' lists the members of your current alliance.\n"
     "If members from different alliances join, all their allies do so.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"announceAlliances",
     "announceAlliances",
     "false",
     &options.announceAlliances,
     valBool,
     tuner_announcealliances,
     "Are changes in alliances made public?\n"
     "If this option is on, changes in alliances are sent to all players\n"
     "and all alliances are shown in the score list. Invitations for\n"
     "alliances are never sent to anyone but the invited players.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"teamPlay",
     "teams",
     "false",
     &options.teamPlay,
     valBool,
     tuner_none,
     "Is the map a team play map?\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"teamFuel",
     "teamFuel",
     "false",
     &options.teamFuel,
     valBool,
     tuner_dummy,
     "Are fuelstations only available to team members?\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"teamCannons",
     "teamCannons",
     "false",
     &options.teamCannons,
     valBool,
     tuner_teamcannons,
     "Do cannons choose sides in teamPlay?\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"cannonSmartness",
     "cannonSmartness",
     "1",
     &options.cannonSmartness,
     valInt,
     tuner_cannonsmartness,
     "0: dumb (straight ahead),\n"
     "1: default (random direction),\n"
     "2: good (small error),\n"
     "3: accurate (aims at predicted player position).\n"
     "Also influences use of weapons if cannonsUseItems is on.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"cannonsUseItems",
     "cannonsPickupItems",
     "false",
     &options.cannonsUseItems,
     valBool,
     tuner_cannonsuseitems,
     "Do cannons use items?\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"cannonsDefend",
     "cannonsDefend",
     "true",
     &options.cannonsDefend,
     valBool,
     tuner_none,
     "Do cannons actively use defensive items like emergency shields and\n"
     "phasing devices?\n"
     "This only works if cannons are actually allowed to use items.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"cannonFlak",
     "cannonAAA",
     "true",
     &options.cannonFlak,
     valBool,
     tuner_dummy,
     "Do cannons fire flak or normal bullets?\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"cannonDeadTime",
     "cannonDeadTime",
     "72",
     &options.cannonDeadTime,
     valSec,
     tuner_dummy,
     "How many seconds do cannons stay dead?\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"cannonDeadTicks",
     "cannonDeadTicks",
     "864.0", /* 72 seconds at gamespeed 12 */
     &options.cannonDeadTicks,
     valReal,
     tuner_dummy,
     "How many ticks do cannons stay dead?\n"
     "Replaces option cannonDeadTime.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"cannonShotSpeed",
     "cannonShotSpeed",
     "21.0",
     &options.cannonShotSpeed,
     valReal,
     tuner_dummy,
     "Speed of cannon shots.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"minCannonShotLife",
     "minCannonShotLife",
     "8.0",
     &options.minCannonShotLife,
     valReal,
     tuner_mincannonshotlife,
     "Minimum life of cannon shots, measured in ticks.\n"
     "If this is set to a value greater than maxCannonShotLife, then\n"
     "maxCannonShotLife will be set to that same value.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"maxCannonShotLife",
     "maxCannonShotLife",
     "32.0",
     &options.maxCannonShotLife,
     valReal,
     tuner_maxcannonshotlife,
     "Maximum life of cannon shots, measured in ticks.\n"
     "If this is set to a value less than minCannonShotLife, then\n"
     "minCannonShotLife will be set to that same value.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"cannonInitialFuel",
     "cannonInitialFuel",
     "0",
     &World.items[ITEM_FUEL].cannon_initial,
     valInt,
     Set_initial_resources,
     "How much fuel cannons start with.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"cannonInitialTanks",
     "cannonInitialTanks",
     "0",
     &World.items[ITEM_TANK].cannon_initial,
     valInt,
     Set_initial_resources,
     "How many tanks cannons start with.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"cannonInitialECMs",
     "cannonInitialECMs",
     "0",
     &World.items[ITEM_ECM].cannon_initial,
     valInt,
     Set_initial_resources,
     "How many ECMs cannons start with.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"cannonInitialArmor",
     "cannonInitialArmors",
     "0",
     &World.items[ITEM_ARMOR].cannon_initial,
     valInt,
     Set_initial_resources,
     "How much armor cannons start with.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"cannonInitialMines",
     "cannonInitialMines",
     "0",
     &World.items[ITEM_MINE].cannon_initial,
     valInt,
     Set_initial_resources,
     "How many mines cannons start with.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"cannonInitialMissiles",
     "cannonInitialMissiles",
     "0",
     &World.items[ITEM_MISSILE].cannon_initial,
     valInt,
     Set_initial_resources,
     "How many missiles cannons start with.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"cannonInitialCloaks",
     "cannonInitialCloaks",
     "0",
     &World.items[ITEM_CLOAK].cannon_initial,
     valInt,
     Set_initial_resources,
     "How many cloaks cannons start with.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"cannonInitialSensors",
     "cannonInitialSensors",
     "0",
     &World.items[ITEM_SENSOR].cannon_initial,
     valInt,
     Set_initial_resources,
     "How many sensors cannons start with.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"cannonInitialWideangles",
     "cannonInitialWideangles",
     "0",
     &World.items[ITEM_WIDEANGLE].cannon_initial,
     valInt,
     Set_initial_resources,
     "How many wideangles cannons start with.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"cannonInitialRearshots",
     "cannonInitialRearshots",
     "0",
     &World.items[ITEM_REARSHOT].cannon_initial,
     valInt,
     Set_initial_resources,
     "How many rearshots cannons start with.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"cannonInitialAfterburners",
     "cannonInitialAfterburners",
     "0",
     &World.items[ITEM_AFTERBURNER].cannon_initial,
     valInt,
     Set_initial_resources,
     "How many afterburners cannons start with.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"cannonInitialTransporters",
     "cannonInitialTransporters",
     "0",
     &World.items[ITEM_TRANSPORTER].cannon_initial,
     valInt,
     Set_initial_resources,
     "How many transporters cannons start with.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"cannonInitialMirrors",
     "cannonInitialMirrors",
     "0",
     &World.items[ITEM_MIRROR].cannon_initial,
     valInt,
     Set_initial_resources,
     "How many mirrors cannons start with.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"cannonInitialDeflectors",
     "cannonInitialDeflectors",
     "0",
     &World.items[ITEM_DEFLECTOR].cannon_initial,
     valInt,
     Set_initial_resources,
     "How many deflectors cannons start with.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"cannonInitialHyperJumps",
     "cannonInitialHyperJumps",
     "0",
     &World.items[ITEM_HYPERJUMP].cannon_initial,
     valInt,
     Set_initial_resources,
     "How many hyperjumps cannons start with.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"cannonInitialPhasings",
     "cannonInitialPhasings",
     "0",
     &World.items[ITEM_PHASING].cannon_initial,
     valInt,
     Set_initial_resources,
     "How many phasing devices cannons start with.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"cannonInitialLasers",
     "cannonInitialLasers",
     "0",
     &World.items[ITEM_LASER].cannon_initial,
     valInt,
     Set_initial_resources,
     "How many lasers cannons start with.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"cannonInitialEmergencyThrusts",
     "cannonInitialEmergencyThrusts",
     "0",
     &World.items[ITEM_EMERGENCY_THRUST].cannon_initial,
     valInt,
     Set_initial_resources,
     "How many emergency thrusts cannons start with.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"cannonInitialTractorBeams",
     "cannonInitialTractorBeams",
     "0",
     &World.items[ITEM_TRACTOR_BEAM].cannon_initial,
     valInt,
     Set_initial_resources,
     "How many tractor/pressor beams cannons start with.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"cannonInitialAutopilots",
     "cannonInitialAutopilots",
     "0",
     &World.items[ITEM_AUTOPILOT].cannon_initial,
     valInt,
     Set_initial_resources,
     "How many autopilots cannons start with.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"cannonInitialEmergencyShields",
     "cannonInitialEmergencyShields",
     "0",
     &World.items[ITEM_EMERGENCY_SHIELD].cannon_initial,
     valInt,
     Set_initial_resources,
     "How many emergency shields cannons start with.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"keepShots",
     "keepShots",
     "false",
     &options.keepShots,
     valBool,
     tuner_dummy,
     "Do shots, mines and missiles remain after their owner leaves?\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"teamAssign",
     "teamAssign",
     "true",
     &options.teamAssign,
     valBool,
     tuner_dummy,
     "If players have not specified which team they like to join\n"
     "should the server choose a team for them automatically?\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"teamImmunity",
     "teamImmunity",
     "true",
     &options.teamImmunity,
     valBool,
     tuner_dummy,
     "Should other team members be immune to various shots thrust etc.?\n"
     "This works for alliances too.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"ecmsReprogramMines",
     "ecmsReprogramMines",
     "true",
     &options.ecmsReprogramMines,
     valBool,
     tuner_dummy,
     "Is it possible to reprogram mines with ECMs?\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"ecmsReprogramRobots",
     "ecmsReprogramRobots",
     "true",
     &options.ecmsReprogramRobots,
     valBool,
     tuner_dummy,
     "Are robots reprogrammed by ECMs instead of blinded?\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"targetKillTeam",
     "targetKillTeam",
     "false",
     &options.targetKillTeam,
     valBool,
     tuner_dummy,
     "Do team members die when their last target explodes?\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"targetTeamCollision",
     "targetCollision",
     "true",
     &options.targetTeamCollision,
     valBool,
     tuner_dummy,
     "Do team members collide with their own target or not.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"targetSync",
     "targetSync",
     "false",
     &options.targetSync,
     valBool,
     tuner_dummy,
     "Do all the targets of a team reappear/repair at the same time?",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"targetDeadTime",
     "targetDeadTime",
     "60",
     &options.targetDeadTime,
     valSec,
     tuner_dummy,
     "How man seconds do targets stay destroyed?\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"treasureKillTeam",
     "treasureKillTeam",
     "false",
     &options.treasureKillTeam,
     valBool,
     tuner_dummy,
     "Do team members die when their treasure is destroyed?\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"captureTheFlag",
     "ctf",
     "false",
     &options.captureTheFlag,
     valBool,
     tuner_dummy,
     "Does a team's treasure have to be safe before enemy balls can be\n"
     "cashed?\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"specialBallTeam",
     "specialBall",
     "-1",
     &options.specialBallTeam,
     valInt,
     tuner_dummy,
     "Balls that belong to this team are 'special' balls that score\n"
     "against all other teams.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"treasureCollisionDestroys",
     "treasureCollisionDestroy",
     "true",
     &options.treasureCollisionDestroys,
     valBool,
     tuner_dummy,
     "Are balls destroyed when a player touches it?\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"ballConnectorSpringConstant",
     "ballConnectorSpringConstant",
     "1500.0",
     &options.ballConnectorSpringConstant,
     valReal,
     tuner_dummy,
     "What is the spring constant for connectors?\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"ballConnectorDamping",
     "ballConnectorDamping",
     "2.0",
     &options.ballConnectorDamping,
     valReal,
     tuner_dummy,
     "What is the damping force on connectors?\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"maxBallConnectorRatio",
     "maxBallConnectorRatio",
     "0.30",
     &options.maxBallConnectorRatio,
     valReal,
     tuner_dummy,
     "How much longer or shorter can a connecter get before it breaks?\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"ballConnectorLength",
     "ballConnectorLength",
     "120.0",
     &options.ballConnectorLength,
     valReal,
     tuner_dummy,
     "How long is a normal connector string?\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},

    // TODO: Remove this setting, it's not used in any maps.
    {"connectorIsString",
     "connectorIsString",
     "false",
     &options.connectorIsString,
     valBool,
     tuner_dummy,
     "Is the ball connector made of string?\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"ballRadius",
     "ballRadius",
     "10.0",
     &options.ballRadius,
     valReal,
     Ball_line_init,
     "What radius, measured in pixels, the treasure balls have on\n"
     "the server. In traditional XPilot, the ball was treated as a\n"
     "point (radius = 0), but visually appeared on the client with\n"
     "a radius of 10 pixels.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"multipleConnectors",
     "multipleBallConnectors",
     "true",
     &options.multipleConnectors,
     valBool,
     tuner_dummy,
     "Can a player connect to multiple balls or just to one?\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"treasureCollisionMayKill",
     "treasureUnshieldedCollisionKills",
     "false",
     &options.treasureCollisionMayKill,
     valBool,
     tuner_dummy,
     "Does a ball kill a player when the player touches it unshielded?\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"wreckageCollisionMayKill",
     "wreckageUnshieldedCollisionKills",
     "false",
     &options.wreckageCollisionMayKill,
     valBool,
     tuner_dummy,
     "Can ships be destroyed when hit by wreckage?\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"asteroidCollisionMayKill",
     "asteroidUnshieldedCollisionKills",
     "true",
     &options.asteroidCollisionMayKill,
     valBool,
     tuner_dummy,
     "Can ships be destroyed when hit by an asteroid?\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"ignore20MaxFPS",
     "ignore20MaxFPS",
     "true",
     &options.ignore20MaxFPS,
     valBool,
     tuner_dummy,
     "Ignore client maxFPS request if it is 20 (the default setting).\n",
     OPT_COMMAND | OPT_DEFAULTS | OPT_VISIBLE},
    {"timing",
     "race",
     "false",
     &options.timing,
     valBool,
     tuner_none,
     "Enable race mode?\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"ballrace",
     "ballrace",
     "false",
     &options.ballrace,
     valBool,
     tuner_dummy,
     "Is timing done for balls (on) or players (off)?\n"
     "Only used if timing is on.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"ballraceConnected",
     "ballraceConnected",
     "false",
     &options.ballrace_connect,
     valBool,
     tuner_dummy,
     "Should a player be connected to a ball to pass a checkpoint?\n"
     "Only used if timing and ballrace are both on.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"edgeWrap",
     "edgeWrap",
     "false",
     &options.edgeWrap,
     valBool,
     tuner_none,
     "Do objects wrap when they cross the edge of the Universe?.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"edgeBounce",
     "edgeBounce",
     "true",
     &options.edgeBounce,
     valBool,
     tuner_dummy,
     "Do objects bounce when they hit the edge of the Universe?.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"extraBorder",
     "extraBorder",
     "false",
     &options.extraBorder,
     valBool,
     tuner_none,
     "Give map an extra border of wall blocks?.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"gravityPoint",
     "gravityPoint",
     "0,0",
     &options.gravityPoint,
     valIPos,
     Compute_gravity,
     "If the gravity is a point source where does that gravity originate?\n"
     "Specify the point in the form: x,y.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"gravityAngle",
     "gravityAngle",
     "90.0",
     &options.gravityAngle,
     valReal,
     Compute_gravity,
     "If gravity is along a uniform line, at what angle is that line?\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"gravityPointSource",
     "gravityPointSource",
     "false",
     &options.gravityPointSource,
     valBool,
     Compute_gravity,
     "Is gravity originating from a single point?\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"gravityClockwise",
     "gravityClockwise",
     "false",
     &options.gravityClockwise,
     valBool,
     Compute_gravity,
     "If the gravity is a point source, is it clockwise?\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"gravityAnticlockwise",
     "gravityAnticlockwise",
     "false",
     &options.gravityAnticlockwise,
     valBool,
     Compute_gravity,
     "If the gravity is a point source, is it anticlockwise?\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"gravityVisible",
     "gravityVisible",
     "true",
     &options.gravityVisible,
     valBool,
     tuner_none,
     "Are gravity mapsymbols visible to players?\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"wormholeVisible",
     "wormholeVisible",
     "true",
     &options.wormholeVisible,
     valBool,
     tuner_none,
     "Are wormhole mapsymbols visible to players?\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"itemConcentratorVisible",
     "itemConcentratorVisible",
     "true",
     &options.itemConcentratorVisible,
     valBool,
     tuner_none,
     "Are itemconcentrator mapsymbols visible to players?\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"asteroidConcentratorVisible",
     "asteroidConcentratorVisible",
     "true",
     &options.asteroidConcentratorVisible,
     valBool,
     tuner_none,
     "Are asteroidconcentrator mapsymbols visible to players?\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"wormTime",
     "wormTime",
     "0",
     &options.wormTime,
     valSec,
     tuner_wormtime,
     "Number of seconds wormholes will remain stable.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {
        "defaultsFileName",
        "defaults",
        NULL,
        &options.defaultsFileName,
        valString,
        tuner_none,
        "The filename of the defaults file to read on startup.\n",
        OPT_COMMAND,
    },
    {
        "passwordFileName",
        "passwordFileName",
        NULL,
        &options.passwordFileName,
        valString,
        tuner_none,
        "The filename of the password file to read on startup.\n",
        OPT_COMMAND | OPT_DEFAULTS,
    },
    {
        "motdFileName",
        "motd",
        NULL,
        &options.motdFileName,
        valString,
        tuner_none,
        "The filename of the MOTD file to show to clients when they join.\n",
        OPT_COMMAND | OPT_DEFAULTS,
    },
    {"scoreTableFileName",
     "scoretable",
     NULL,
     &options.scoreTableFileName,
     valString,
     tuner_none,
     "The filename for the score table to be dumped to.\n"
     "This is a placeholder option which doesn't do anything.\n",
     OPT_COMMAND | OPT_DEFAULTS},
    {"adminMessageFileName",
     "adminMessage",
     conf_logfile_string,
     &options.adminMessageFileName,
     valString,
     tuner_none,
     "The name of the file where player messages for the\n"
     "server administrator will be saved.  For the messages\n"
     "to be saved the file must already exist.  Players can\n"
     "send these messages by writing to god.",
     OPT_COMMAND | OPT_DEFAULTS},
    {"adminMessageFileSizeLimit",
     "adminMessageLimit",
     "20202", /* kps - ??? */
     &options.adminMessageFileSizeLimit,
     valInt,
     tuner_none,
     "The maximum size in bytes of the admin message file.\n",
     OPT_COMMAND | OPT_DEFAULTS},
    {"framesPerSecond",
     "FPS",
     "14",
     &options.framesPerSecond,
     valInt,
     Timing_setup,
     "The number of frames per second the server should strive for.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"allowSmartMissiles",
     "allowSmarts",
     "true",
     &options.allowSmartMissiles,
     valBool,
     tuner_dummy,
     "Should smart missiles be allowed?\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"allowHeatSeekers",
     "allowHeats",
     "true",
     &options.allowHeatSeekers,
     valBool,
     tuner_dummy,
     "Should heatseekers be allowed?\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"allowTorpedoes",
     "allowTorps",
     "true",
     &options.allowTorpedoes,
     valBool,
     tuner_dummy,
     "Should torpedoes be allowed?\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"allowNukes",
     "nukes",
     "false",
     &options.allowNukes,
     valBool,
     tuner_modifiers,
     "Should nuclear weapons be allowed?\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"allowClusters",
     "clusters",
     "false",
     &options.allowClusters,
     valBool,
     tuner_modifiers,
     "Should cluster weapons be allowed?\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"allowModifiers",
     "modifiers",
     "false",
     &options.allowModifiers,
     valBool,
     tuner_modifiers,
     "Should the weapon modifiers be allowed?\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"allowLaserModifiers",
     "lasermodifiers",
     "false",
     &options.allowLaserModifiers,
     valBool,
     tuner_modifiers,
     "Can lasers be modified to be a different weapon?\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"allowShipShapes",
     "ShipShapes",
     "true",
     &options.allowShipShapes,
     valBool,
     tuner_none,
     "Are players allowed to define their own ship shape?\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"playersOnRadar",
     "playersRadar",
     "true",
     &options.playersOnRadar,
     valBool,
     tuner_dummy,
     "Are players visible on the radar.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"missilesOnRadar",
     "missilesRadar",
     "true",
     &options.missilesOnRadar,
     valBool,
     tuner_dummy,
     "Are missiles visible on the radar.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"minesOnRadar",
     "minesRadar",
     "false",
     &options.minesOnRadar,
     valBool,
     tuner_dummy,
     "Are mines visible on the radar.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"nukesOnRadar",
     "nukesRadar",
     "true",
     &options.nukesOnRadar,
     valBool,
     tuner_dummy,
     "Are nukes visible or highlighted on the radar.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"treasuresOnRadar",
     "treasuresRadar",
     "false",
     &options.treasuresOnRadar,
     valBool,
     tuner_dummy,
     "Are treasure balls visible or highlighted on the radar.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"asteroidsOnRadar",
     "asteroidsRadar",
     "false",
     &options.asteroidsOnRadar,
     valBool,
     tuner_dummy,
     "Are asteroids visible on the radar.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"distinguishMissiles",
     "distinguishMissiles",
     "true",
     &options.distinguishMissiles,
     valBool,
     tuner_dummy,
     "Are different types of missiles distinguished (by length).\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"maxMissilesPerPack",
     "maxMissilesPerPack",
     "4",
     &options.maxMissilesPerPack,
     valInt,
     Tune_item_packs,
     "The number of missiles gotten by picking up one missile item.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"maxMinesPerPack",
     "maxMinesPerPack",
     "2",
     &options.maxMinesPerPack,
     valInt,
     Tune_item_packs,
     "The number of mines gotten by picking up one mine item.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"identifyMines",
     "identifyMines",
     "true",
     &options.identifyMines,
     valBool,
     tuner_dummy,
     "Are mine owner's names displayed.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"shieldedItemPickup",
     "shieldItem",
     "false",
     &options.shieldedItemPickup,
     valBool,
     tuner_dummy,
     "Can items be picked up while shields are up?\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"shieldedMining",
     "shieldMine",
     "false",
     &options.shieldedMining,
     valBool,
     tuner_dummy,
     "Can mines be thrown and placed while shields are up?\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"laserIsStunGun",
     "stunGun",
     "false",
     &options.laserIsStunGun,
     valBool,
     tuner_dummy,
     "Is the laser weapon a stun gun weapon?\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"nukeMinSmarts",
     "nukeMinSmarts",
     "7",
     &options.nukeMinSmarts,
     valInt,
     tuner_dummy,
     "The minimum number of missiles needed to fire one nuclear missile.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"nukeMinMines",
     "nukeMinMines",
     "4",
     &options.nukeMinMines,
     valInt,
     tuner_dummy,
     "The minimum number of mines needed to make a nuclear mine.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"nukeClusterDamage",
     "nukeClusterDamage",
     "1.0",
     &options.nukeClusterDamage,
     valReal,
     tuner_dummy,
     "How much each cluster debris does damage wise from a nuke mine.\n"
     "This helps to reduce the number of particles caused by nuclear mine\n"
     "explosions, which improves server response time for such explosions.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"mineFuseTime",
     "mineFuseTime",
     "0.0",
     &options.mineFuseTime,
     valSec,
     tuner_dummy,
     "Number of seconds after which owned mines become deadly, zero means never.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"mineLife",
     "mineLife",
     "0",
     &options.mineLife,
     valInt,
     tuner_minelife,
     "Life of mines in ticks, zero means use default.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"minMineSpeed",
     "minMineSpeed",
     "0",
     &options.minMineSpeed,
     valReal,
     tuner_dummy,
     "Minimum speed of mines.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"missileLife",
     "missileLife",
     "0",
     &options.missileLife,
     valInt,
     tuner_missilelife,
     "Life of missiles in ticks, zero means use default.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"baseMineRange",
     "baseMineRange",
     "0",
     &options.baseMineRange,
     valInt,
     tuner_dummy,
     "Range within which mines/bombs are not allowed.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"mineShotDetonateDistance",
     "mineShotDetonateDistance",
     "0",
     &options.mineShotDetonateDistance,
     valInt,
     tuner_dummy,
     "How close must a shot be to detonate a mine?\n"
     "Set this to 0 to turn it off.",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"shotKillScoreMult",
     "shotKillScoreMult",
     "1.0",
     &options.shotKillScoreMult,
     valReal,
     tuner_dummy,
     "Multiplication factor to scale score for shot kills.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"torpedoKillScoreMult",
     "torpedoKillScoreMult",
     "1.0",
     &options.torpedoKillScoreMult,
     valReal,
     tuner_dummy,
     "Multiplication factor to scale score for torpedo kills.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"smartKillScoreMult",
     "smartKillScoreMult",
     "1.0",
     &options.smartKillScoreMult,
     valReal,
     tuner_dummy,
     "Multiplication factor to scale score for smart missile kills.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"heatKillScoreMult",
     "heatKillScoreMult",
     "1.0",
     &options.heatKillScoreMult,
     valReal,
     tuner_dummy,
     "Multiplication factor to scale score for heatseeker kills.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"clusterKillScoreMult",
     "clusterKillScoreMult",
     "1.0",
     &options.clusterKillScoreMult,
     valReal,
     tuner_dummy,
     "Multiplication factor to scale score for cluster debris kills.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"laserKillScoreMult",
     "laserKillScoreMult",
     "1.0",
     &options.laserKillScoreMult,
     valReal,
     tuner_dummy,
     "Multiplication factor to scale score for laser kills.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"tankKillScoreMult",
     "tankKillScoreMult",
     "0.44",
     &options.tankKillScoreMult,
     valReal,
     tuner_dummy,
     "Multiplication factor to scale score for tank kills.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"runoverKillScoreMult",
     "runoverKillScoreMult",
     "0.33",
     &options.runoverKillScoreMult,
     valReal,
     tuner_dummy,
     "Multiplication factor to scale score for player runovers.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"ballKillScoreMult",
     "ballKillScoreMult",
     "1.0",
     &options.ballKillScoreMult,
     valReal,
     tuner_dummy,
     "Multiplication factor to scale score for ball kills.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"explosionKillScoreMult",
     "explosionKillScoreMult",
     "0.33",
     &options.explosionKillScoreMult,
     valReal,
     tuner_dummy,
     "Multiplication factor to scale score for explosion kills.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"shoveKillScoreMult",
     "shoveKillScoreMult",
     "0.5",
     &options.shoveKillScoreMult,
     valReal,
     tuner_dummy,
     "Multiplication factor to scale score for shove kills.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"crashScoreMult",
     "crashScoreMult",
     "0.33",
     &options.crashScoreMult,
     valReal,
     tuner_dummy,
     "Multiplication factor to scale score for player crashes.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"mineScoreMult",
     "mineScoreMult",
     "0.17",
     &options.mineScoreMult,
     valReal,
     tuner_dummy,
     "Multiplication factor to scale score for mine hits.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"selfKillScoreMult",
     "selfKillScoreMult",
     "0.5",
     &options.selfKillScoreMult,
     valReal,
     tuner_dummy,
     "Multiplication factor to scale score for killing yourself.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"unownedKillScoreMult",
     "unownedKillScoreMult",
     "0.5",
     &options.unownedKillScoreMult,
     valReal,
     tuner_dummy,
     "Multiplication factor to scale score for being killed by asteroids\n"
     "or other objects without an owner.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"asteroidPoints",
     "asteroidPoints",
     "1.0",
     &options.asteroidPoints,
     valReal,
     tuner_dummy,
     "Points awarded for breaking an asteroid.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"cannonPoints",
     "cannonPoints",
     "1.0",
     &options.cannonPoints,
     valReal,
     tuner_dummy,
     "Points awarded for killing a cannon.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"asteroidMaxScore",
     "asteroidMaxScore",
     "100.0",
     &options.asteroidMaxScore,
     valReal,
     tuner_dummy,
     "Maximum score to receive points for breaking an asteroid.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"cannonMaxScore",
     "cannonMaxScore",
     "100.0",
     &options.cannonMaxScore,
     valReal,
     tuner_dummy,
     "Maximum score to receive points for killing a cannon.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"movingItemProb",
     "movingItemProb",
     "0.2",
     &options.movingItemProb,
     valReal,
     Set_misc_item_limits,
     "Probability for an item to appear as moving.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"randomItemProb",
     "randomItemProb",
     "0.0",
     &options.randomItemProb,
     valReal,
     Set_misc_item_limits,
     "Probability for an item to appear random.\n"
     "Random items change their appearance every frame, so players\n"
     "cannot tell what item they have until they get it.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"dropItemOnKillProb",
     "dropItemOnKillProb",
     "0.5",
     &options.dropItemOnKillProb,
     valReal,
     Set_misc_item_limits,
     "Probability for dropping an item (each item) when you are killed.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"detonateItemOnKillProb",
     "detonateItemOnKillProb",
     "0.5",
     &options.detonateItemOnKillProb,
     valReal,
     Set_misc_item_limits,
     "Probability for undropped items to detonate when you are killed.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"destroyItemInCollisionProb",
     "destroyItemInCollisionProb",
     "0.0",
     &options.destroyItemInCollisionProb,
     valReal,
     Set_misc_item_limits,
     "Probability for items (some items) to be destroyed in a collision.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"asteroidItemProb",
     "asteroidItemProb",
     "0.0",
     &options.asteroidItemProb,
     valReal,
     Set_misc_item_limits,
     "Probability for an asteroid to release items when it breaks.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"asteroidMaxItems",
     "asteroidMaxItems",
     "0",
     &options.asteroidMaxItems,
     valInt,
     Set_misc_item_limits,
     "The maximum number of items a broken asteroid can release.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"itemProbMult",
     "itemProbFact",
     "1.0",
     &options.itemProbMult,
     valReal,
     Tune_item_probs,
     "Item Probability Multiplication Factor scales all item probabilities.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"cannonItemProbMult",
     "cannonItemProbMult",
     "1.0",
     &options.cannonItemProbMult,
     valReal,
     tuner_dummy,
     "Average number of items a cannon gets per minute.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"maxItemDensity",
     "maxItemDensity",
     "0.00012",
     &options.maxItemDensity,
     valReal,
     Tune_item_probs,
     "Maximum density [0.0-1.0] for items (max items per block).\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"asteroidProb",
     "asteroidProb",
     "5e-7",
     &World.asteroids.prob,
     valReal,
     Tune_asteroid_prob,
     "Probability for an asteroid to appear.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"maxAsteroidDensity",
     "maxAsteroidDensity",
     "0",
     &options.maxAsteroidDensity,
     valReal,
     Tune_asteroid_prob,
     "Maximum density [0.0-1.0] for asteroids (max asteroids per block.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"itemConcentratorRadius",
     "itemConcentratorRange",
     "10",
     &options.itemConcentratorRadius,
     valInt,
     Set_misc_item_limits,
     "The maximum distance from an item concentator for items to appear in.\n"
     "Sensible values are in the range 1 to 20.\n"
     "If no item concentators are defined in a map then items can popup anywhere.\n"
     "If any are any then items popup in the vicinity of an item concentrator\n"
     "with probability itemConcentratorProb and anywhere the remainder of the time.\n"
     "An item concentrator is drawn on screen as three rotating triangles.\n"
     "The map symbol is the percentage symbol '%'.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"itemConcentratorProb",
     "itemConcentratorProb",
     "1.0",
     &options.itemConcentratorProb,
     valReal,
     Set_misc_item_limits,
     "The probability, if any item concentrators are present, that they will be\n"
     "used.  This proportion of items will be placed near item concentrators,\n"
     "within itemConcentratorRadius.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"asteroidConcentratorRadius",
     "asteroidConcentratorRange",
     "10",
     &options.asteroidConcentratorRadius,
     valInt,
     Tune_asteroid_prob,
     "The maximum distance from an asteroid concentrator for asteroids to\n"
     "appear in.  Sensible values are in the range 1 to 20.\n"
     "If no asteroid concentrators are defined in a map then asteroids can\n"
     "popup anywhere.  If any are then asteroids popup in the vicinity of an\n"
     "asteroid concentrator with probability asteroidConcentratorProb and anywhere\n"
     "the remainder of the time.  An asteroid concentrator is drawn on the\n"
     "screen as three rotating squares.  The map symbol is the ampersand\n"
     "'&options.'.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"asteroidConcentratorProb",
     "asteroidConcentratorProb",
     "1.0",
     &options.asteroidConcentratorProb,
     valReal,
     Tune_asteroid_prob,
     "The probability, if any asteroid concentrators are present, that they will\n"
     "be used.  This proportion of asteroids will be placed near asteroid\n"
     "concentrators, within asteroidConcentratorRadius.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"rogueHeatProb",
     "rogueHeatProb",
     "1.0",
     &options.rogueHeatProb,
     valReal,
     tuner_dummy,
     "Probability that unclaimed missile packs will go rogue.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"rogueMineProb",
     "rogueMineProb",
     "1.0",
     &options.rogueMineProb,
     valReal,
     tuner_dummy,
     "Probability that unclaimed mine items will activate.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"itemEnergyPackProb",
     "itemEnergyPackProb",
     "1e-9",
     &World.items[ITEM_FUEL].prob,
     valReal,
     Tune_item_probs,
     "Probability for an energy pack to appear.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"itemTankProb",
     "itemTankProb",
     "1e-9",
     &World.items[ITEM_TANK].prob,
     valReal,
     Tune_item_probs,
     "Probability for an extra tank to appear.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"itemECMProb",
     "itemECMProb",
     "1e-9",
     &World.items[ITEM_ECM].prob,
     valReal,
     Tune_item_probs,
     "Probability for an ECM item to appear.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"itemArmorProb",
     "itemArmorProb",
     "1e-9",
     &World.items[ITEM_ARMOR].prob,
     valReal,
     Tune_item_probs,
     "Probability for an armor item to appear.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"itemMineProb",
     "itemMineProb",
     "1e-9",
     &World.items[ITEM_MINE].prob,
     valReal,
     Tune_item_probs,
     "Probability for a mine item to appear.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"itemMissileProb",
     "itemMissileProb",
     "1e-9",
     &World.items[ITEM_MISSILE].prob,
     valReal,
     Tune_item_probs,
     "Probability for a missile item to appear.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"itemCloakProb",
     "itemCloakProb",
     "1e-9",
     &World.items[ITEM_CLOAK].prob,
     valReal,
     Tune_item_probs,
     "Probability for a cloak item to appear.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"itemSensorProb",
     "itemSensorProb",
     "1e-9",
     &World.items[ITEM_SENSOR].prob,
     valReal,
     Tune_item_probs,
     "Probability for a sensor item to appear.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"itemWideangleProb",
     "itemWideangleProb",
     "1e-9",
     &World.items[ITEM_WIDEANGLE].prob,
     valReal,
     Tune_item_probs,
     "Probability for a wideangle item to appear.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"itemRearshotProb",
     "itemRearshotProb",
     "1e-9",
     &World.items[ITEM_REARSHOT].prob,
     valReal,
     Tune_item_probs,
     "Probability for a rearshot item to appear.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"itemAfterburnerProb",
     "itemAfterburnerProb",
     "1e-9",
     &World.items[ITEM_AFTERBURNER].prob,
     valReal,
     Tune_item_probs,
     "Probability for an afterburner item to appear.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"itemTransporterProb",
     "itemTransporterProb",
     "1e-9",
     &World.items[ITEM_TRANSPORTER].prob,
     valReal,
     Tune_item_probs,
     "Probability for a transporter item to appear.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"itemMirrorProb",
     "itemMirrorProb",
     "1e-9",
     &World.items[ITEM_MIRROR].prob,
     valReal,
     Tune_item_probs,
     "Probability for a mirror item to appear.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"itemDeflectorProb",
     "itemDeflectorProb",
     "1e-9",
     &World.items[ITEM_DEFLECTOR].prob,
     valReal,
     Tune_item_probs,
     "Probability for a deflector item to appear.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"itemHyperJumpProb",
     "itemHyperJumpProb",
     "1e-9",
     &World.items[ITEM_HYPERJUMP].prob,
     valReal,
     Tune_item_probs,
     "Probability for a hyperjump item to appear.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"itemPhasingProb",
     "itemPhasingProb",
     "1e-9",
     &World.items[ITEM_PHASING].prob,
     valReal,
     Tune_item_probs,
     "Probability for a phasing item to appear.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"itemLaserProb",
     "itemLaserProb",
     "1e-9",
     &World.items[ITEM_LASER].prob,
     valReal,
     Tune_item_probs,
     "Probability for a Laser item to appear.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"itemEmergencyThrustProb",
     "itemEmergencyThrustProb",
     "1e-9",
     &World.items[ITEM_EMERGENCY_THRUST].prob,
     valReal,
     Tune_item_probs,
     "Probability for an Emergency Thrust item to appear.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"itemTractorBeamProb",
     "itemTractorBeamProb",
     "1e-9",
     &World.items[ITEM_TRACTOR_BEAM].prob,
     valReal,
     Tune_item_probs,
     "Probability for a Tractor Beam item to appear.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"itemAutopilotProb",
     "itemAutopilotProb",
     "1e-9",
     &World.items[ITEM_AUTOPILOT].prob,
     valReal,
     Tune_item_probs,
     "Probability for an Autopilot item to appear.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"itemEmergencyShieldProb",
     "itemEmergencyShieldProb",
     "1e-9",
     &World.items[ITEM_EMERGENCY_SHIELD].prob,
     valReal,
     Tune_item_probs,
     "Probability for an Emergency Shield item to appear.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"initialFuel",
     "initialFuel",
     "1000",
     &World.items[ITEM_FUEL].initial,
     valInt,
     Set_initial_resources,
     "How much fuel players start with, or the minimum after being killed.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"initialTanks",
     "initialTanks",
     "0",
     &World.items[ITEM_TANK].initial,
     valInt,
     Set_initial_resources,
     "How many tanks players start with.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"initialECMs",
     "initialECMs",
     "0",
     &World.items[ITEM_ECM].initial,
     valInt,
     Set_initial_resources,
     "How many ECMs players start with.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"initialArmor",
     "initialArmors",
     "0",
     &World.items[ITEM_ARMOR].initial,
     valInt,
     Set_initial_resources,
     "How much armor players start with.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"initialMines",
     "initialMines",
     "0",
     &World.items[ITEM_MINE].initial,
     valInt,
     Set_initial_resources,
     "How many mines players start with.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"initialMissiles",
     "initialMissiles",
     "0",
     &World.items[ITEM_MISSILE].initial,
     valInt,
     Set_initial_resources,
     "How many missiles players start with.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"initialCloaks",
     "initialCloaks",
     "0",
     &World.items[ITEM_CLOAK].initial,
     valInt,
     Set_initial_resources,
     "How many cloaks players start with.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"initialSensors",
     "initialSensors",
     "0",
     &World.items[ITEM_SENSOR].initial,
     valInt,
     Set_initial_resources,
     "How many sensors players start with.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"initialWideangles",
     "initialWideangles",
     "0",
     &World.items[ITEM_WIDEANGLE].initial,
     valInt,
     Set_initial_resources,
     "How many wideangles players start with.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"initialRearshots",
     "initialRearshots",
     "0",
     &World.items[ITEM_REARSHOT].initial,
     valInt,
     Set_initial_resources,
     "How many rearshots players start with.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"initialAfterburners",
     "initialAfterburners",
     "0",
     &World.items[ITEM_AFTERBURNER].initial,
     valInt,
     Set_initial_resources,
     "How many afterburners players start with.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"initialTransporters",
     "initialTransporters",
     "0",
     &World.items[ITEM_TRANSPORTER].initial,
     valInt,
     Set_initial_resources,
     "How many transporters players start with.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"initialMirrors",
     "initialMirrors",
     "0",
     &World.items[ITEM_MIRROR].initial,
     valInt,
     Set_initial_resources,
     "How many mirrors players start with.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"initialDeflectors",
     "initialDeflectors",
     "0",
     &World.items[ITEM_DEFLECTOR].initial,
     valInt,
     Set_initial_resources,
     "How many deflectors players start with.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"initialHyperJumps",
     "initialHyperJumps",
     "0",
     &World.items[ITEM_HYPERJUMP].initial,
     valInt,
     Set_initial_resources,
     "How many hyperjumps players start with.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"initialPhasings",
     "initialPhasings",
     "0",
     &World.items[ITEM_PHASING].initial,
     valInt,
     Set_initial_resources,
     "How many phasing devices players start with.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"initialLasers",
     "initialLasers",
     "0",
     &World.items[ITEM_LASER].initial,
     valInt,
     Set_initial_resources,
     "How many lasers players start with.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"initialEmergencyThrusts",
     "initialEmergencyThrusts",
     "0",
     &World.items[ITEM_EMERGENCY_THRUST].initial,
     valInt,
     Set_initial_resources,
     "How many emergency thrusts players start with.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"initialTractorBeams",
     "initialTractorBeams",
     "0",
     &World.items[ITEM_TRACTOR_BEAM].initial,
     valInt,
     Set_initial_resources,
     "How many tractor/pressor beams players start with.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"initialAutopilots",
     "initialAutopilots",
     "0",
     &World.items[ITEM_AUTOPILOT].initial,
     valInt,
     Set_initial_resources,
     "How many autopilots players start with.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"initialEmergencyShields",
     "initialEmergencyShields",
     "0",
     &World.items[ITEM_EMERGENCY_SHIELD].initial,
     valInt,
     Set_initial_resources,
     "How many emergency shields players start with.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"maxFuel",
     "maxFuel",
     "10000",
     &World.items[ITEM_FUEL].limit,
     valInt,
     Set_initial_resources,
     "Upper limit on the amount of fuel per player.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"maxTanks",
     "maxTanks",
     "8",
     &World.items[ITEM_TANK].limit,
     valInt,
     Set_initial_resources,
     "Upper limit on the number of tanks per player.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"maxECMs",
     "maxECMs",
     "10",
     &World.items[ITEM_ECM].limit,
     valInt,
     Set_initial_resources,
     "Upper limit on the number of ECMs per player.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"maxMines",
     "maxMines",
     "10",
     &World.items[ITEM_MINE].limit,
     valInt,
     Set_initial_resources,
     "Upper limit on the number of mines per player.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"maxMissiles",
     "maxMissiles",
     "10",
     &World.items[ITEM_MISSILE].limit,
     valInt,
     Set_initial_resources,
     "Upper limit on the number of missiles per player.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"maxCloaks",
     "maxCloaks",
     "10",
     &World.items[ITEM_CLOAK].limit,
     valInt,
     Set_initial_resources,
     "Upper limit on the number of cloaks per player.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"maxSensors",
     "maxSensors",
     "10",
     &World.items[ITEM_SENSOR].limit,
     valInt,
     Set_initial_resources,
     "Upper limit on the number of sensors per player.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"maxWideangles",
     "maxWideangles",
     "10",
     &World.items[ITEM_WIDEANGLE].limit,
     valInt,
     Set_initial_resources,
     "Upper limit on the number of wides per player.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"maxRearshots",
     "maxRearshots",
     "10",
     &World.items[ITEM_REARSHOT].limit,
     valInt,
     Set_initial_resources,
     "Upper limit on the number of rearshots per player.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"maxAfterburners",
     "maxAfterburners",
     "10",
     &World.items[ITEM_AFTERBURNER].limit,
     valInt,
     Set_initial_resources,
     "Upper limit on the number of afterburners per player.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"maxTransporters",
     "maxTransporters",
     "10",
     &World.items[ITEM_TRANSPORTER].limit,
     valInt,
     Set_initial_resources,
     "Upper limit on the number of transporters per player.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"maxArmor",
     "maxArmors",
     "10",
     &World.items[ITEM_ARMOR].limit,
     valInt,
     Set_initial_resources,
     "Upper limit on the amount of armor per player.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"maxMirrors",
     "maxMirrors",
     "10",
     &World.items[ITEM_MIRROR].limit,
     valInt,
     Set_initial_resources,
     "Upper limit on the number of mirrors per player.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"maxDeflectors",
     "maxDeflectors",
     "10",
     &World.items[ITEM_DEFLECTOR].limit,
     valInt,
     Set_initial_resources,
     "Upper limit on the number of deflectors per player.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"maxPhasings",
     "maxPhasings",
     "10",
     &World.items[ITEM_PHASING].limit,
     valInt,
     Set_initial_resources,
     "Upper limit on the number of phasing devices per players.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"maxHyperJumps",
     "maxHyperJumps",
     "10",
     &World.items[ITEM_HYPERJUMP].limit,
     valInt,
     Set_initial_resources,
     "Upper limit on the number of hyperjumps per player.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"maxEmergencyThrusts",
     "maxEmergencyThrusts",
     "10",
     &World.items[ITEM_EMERGENCY_THRUST].limit,
     valInt,
     Set_initial_resources,
     "Upper limit on the number of emergency thrusts per player.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"maxLasers",
     "maxLasers",
     "5",
     &World.items[ITEM_LASER].limit,
     valInt,
     Set_initial_resources,
     "Upper limit on the number of lasers per player.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"maxTractorBeams",
     "maxTractorBeams",
     "4",
     &World.items[ITEM_TRACTOR_BEAM].limit,
     valInt,
     Set_initial_resources,
     "Upper limit on the number of tractorbeams per player.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"maxAutopilots",
     "maxAutopilots",
     "10",
     &World.items[ITEM_AUTOPILOT].limit,
     valInt,
     Set_initial_resources,
     "Upper limit on the number of autopilots per player.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"maxEmergencyShields",
     "maxEmergencyShields",
     "10",
     &World.items[ITEM_EMERGENCY_SHIELD].limit,
     valInt,
     Set_initial_resources,
     "Upper limit on the number of emergency shields per player.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"gameDuration",
     "time",
     "0.0",
     &options.gameDuration,
     valReal,
     tuner_gameduration,
     "The duration of the game in minutes (aka. pizza mode).\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"allowViewing",
     "allowViewing",
     "false",
     &options.allowViewing,
     valBool,
     tuner_dummy,
     "Are players allowed to watch any other player while paused, waiting or dead?\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"survivalScore",
     "survivalScore",
     "0.0",
     &options.survivalScore,
     valReal,
     tuner_dummy,
     "Multiplicator for quadratic score increase over time \n"
     "survived with lowered shield",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    // {"pauseTax",
    //  "pauseTax",
    //  "0.0",
    //  &options.pauseTax,
    //  valReal,
    //  tuner_dummy,
    //  "How many points to subtract from pausing players each second.\n",
    //  OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"friction",
     "friction",
     "0.0",
     &options.frictionSetting,
     valReal,
     tuner_dummy,
     "Fraction of velocity ship loses each frame.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"blockFriction",
     "blockFriction",
     "0.0",
     &options.blockFriction,
     valReal,
     tuner_dummy,
     "Fraction of velocity ship loses each frame when it is in friction blocks.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"blockFrictionVisible",
     "blockFrictionVisible",
     "true",
     &options.blockFrictionVisible,
     valBool,
     tuner_none,
     "Are friction blocks visible?\n"
     "If true, friction blocks show up as decor; if false, they don't show up at all.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"coriolis",
     "coriolis",
     "0",
     &options.coriolis,
     valInt,
     tuner_dummy,
     "The clockwise angle (in degrees) a ship's velocity turns each frame.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"checkpointRadius",
     "checkpointRadius",
     "6.0",
     &options.checkpointRadius,
     valReal,
     tuner_dummy,
     "How close you have to be to a checkpoint to register - in blocks.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"raceLaps",
     "raceLaps",
     "3",
     &options.raceLaps,
     valInt,
     tuner_racelaps,
     "How many laps a race is run over.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"lockOtherTeam",
     "lockOtherTeam",
     "true",
     &options.lockOtherTeam,
     valBool,
     tuner_dummy,
     "Can you lock on players from other teams when you're dead.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"loseItemDestroys",
     "loseItemDestroys",
     "false",
     &options.loseItemDestroys,
     valBool,
     tuner_dummy,
     "Destroy item that player drops. Otherwise drop it.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"useWreckage",
     "useWreckage",
     "true",
     &options.useWreckage,
     valBool,
     tuner_dummy,
     "Do destroyed ships leave wreckage?\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"maxOffensiveItems",
     "maxOffensiveItems",
     "100",
     &options.maxOffensiveItems,
     valInt,
     tuner_dummy,
     "How many offensive items a player can carry.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"maxDefensiveItems",
     "maxDefensiveItems",
     "100",
     &options.maxDefensiveItems,
     valInt,
     tuner_dummy,
     "How many defensive items a player can carry.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"maxRoundTime",
     "maxRoundTime",
     "0",
     &options.maxRoundTime,
     valInt,
     tuner_dummy,
     "The maximum duration of each round, in seconds.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"roundsToPlay",
     "numRounds",
     "0",
     &options.roundsToPlay,
     valInt,
     tuner_dummy,
     "The number of rounds to play.  Unlimited if 0.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"maxVisibleObject",
     "maxVisibleObjects",
     "1000",
     &options.maxVisibleObject,
     valInt,
     tuner_dummy,
     "What is the maximum number of objects a player can see.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"pLockServer",
     "pLockServer",
#ifdef PLOCKSERVER
     "true",
#else
     "false",
#endif
     &options.pLockServer,
     valBool,
     tuner_plock,
     "Whether the server is prevented from being swapped out of memory.\n",
     OPT_COMMAND | OPT_DEFAULTS | OPT_VISIBLE},
    {"timerResolution",
     "timerResolution",
     "0",
     &options.timerResolution,
     valInt,
     tuner_none,
     "If set to nonzero xpilots will requests signals from the OS at\n"
     "1/timerResolution second intervals.  The server will then compute\n"
     "a new frame FPS times out of every timerResolution signals.\n",
     OPT_COMMAND | OPT_DEFAULTS | OPT_VISIBLE},
    {"password",
     "password",
     NULL,
     &options.password,
     valString,
     tuner_dummy,
     "The password needed to obtain operator privileges.\n"
     "If specified on the command line, on many systems other\n"
     "users will be able to see the password.  Therefore, using\n"
     "the password file instead is recommended.",
     OPT_COMMAND | OPT_DEFAULTS | OPT_PASSWORD},
    {"clientPortStart",
     "clientPortStart",
     "0",
     &options.clientPortStart,
     valInt,
     tuner_dummy,
     "Use UDP ports clientPortStart - clientPortEnd (for firewalls)\n",
     OPT_COMMAND | OPT_DEFAULTS | OPT_VISIBLE},
    {"clientPortEnd",
     "clientPortEnd",
     "0",
     &options.clientPortEnd,
     valInt,
     tuner_dummy,
     "Use UDP ports clientPortStart - clientPortEnd (for firewalls)\n",
     OPT_COMMAND | OPT_DEFAULTS | OPT_VISIBLE},
    {"maxPauseTime",
     "maxPauseTime",
     "14400", /* can pause 4 hours by default */
     &options.maxPauseTime,
     valInt,
     tuner_dummy,
     "The maximum time a player can stay paused for, in seconds.\n"
     "After being paused this long, the player will be kicked off.\n"
     "Setting this option to 0 disables the feature.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"dataURL",
     "dataURL",
     "",
     &options.dataURL,
     valString,
     tuner_dummy,
     "URL where the client can get extra data for this map.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
    {"polygonMode",
     "polygonMode",
     "false",
     &options.polygonMode,
     valBool,
     tuner_dummy,
     "Force use of polygon protocol when communicating with clients?\n"
     "(useful for debugging if you want to see the polygons created\n"
     "in the blocks to polygons conversion function).\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},

    /* teamcup related options */
    {
        "teamcup",
        "teamcup",
        "false",
        &options.teamcup,
        valBool,
        tuner_none,
        "Is this a teamcup match?.\n",
        OPT_ORIGIN_ANY},
    {"teamcupName",
     "teamcupName",
     "",
     &options.teamcupName,
     valString,
     tuner_none,
     "The name of the teamcup (used only if teamcup is true).\n",
     OPT_ORIGIN_ANY},
    {"teamcupMailAddress",
     "teamcupMailAddress",
     "",
     &options.teamcupMailAddress,
     valString,
     tuner_none,
     "The mail address where players should send match results.\n",
     OPT_ORIGIN_ANY},
    {"teamcupScoreFileNamePrefix",
     "teamcupScoreFileNamePrefix",
     "",
     &options.teamcupScoreFileNamePrefix,
     valString,
     tuner_none,
     "First part of file name for teamcup score files.\n"
     "The whole filename will be this followed by the match number.\n",
     OPT_ORIGIN_ANY},
    {"teamcupMatchNumber",
     "match",
     "0",
     &options.teamcupMatchNumber,
     valInt,
     tuner_dummy,
     "The number of the teamcup match.\n",
     OPT_COMMAND | OPT_VISIBLE},
    {"mainLoopTime",
     "mainLoopTime",
     "0",
     &options.mainLoopTime,
     valReal,
     tuner_none,
     "Duration of last Main_loop() function call (in milliseconds).\n"
     "This option is read only.\n",
     OPT_COMMAND | OPT_VISIBLE},
    {"cellGetObjectsThreshold",
     "cellThreshold",
     "500",
     &options.cellGetObjectsThreshold,
     valInt,
     tuner_dummy,
     "Use Cell_get_objects if there is this many objects or more.\n",
     OPT_ORIGIN_ANY | OPT_VISIBLE},
};

static bool options_inited = false;

option_desc *Get_option_descs(int *count_ptr)
{
    if (!options_inited)
        dumpcore("options not initialized");

    *count_ptr = NELEM(opts);
    return &opts[0];
}

static void Init_default_options(void)
{
    option_desc *desc;

    if ((desc = Find_option_by_name("mapFileName")) == NULL)
        dumpcore("Could not find map file option");

    desc->defaultValue = Conf_default_map();
    if ((desc = Find_option_by_name("motdFileName")) == NULL)
        dumpcore("Could not find motd file option");

    desc->defaultValue = Conf_servermotdfile();
    if ((desc = Find_option_by_name("robotFile")) == NULL)
        dumpcore("Could not find robot file option");

    desc->defaultValue = Conf_robotfile();
    if ((desc = Find_option_by_name("defaultsFileName")) == NULL)
        dumpcore("Could not find defaults file option");

    desc->defaultValue = Conf_defaults_file_name();
    if ((desc = Find_option_by_name("passwordFileName")) == NULL)
        dumpcore("Could not find password file option");

    desc->defaultValue = Conf_password_file_name();
}

bool Init_options(void)
{
    int i, option_count = NELEM(opts);

    if (options_inited)
        dumpcore("Can't init options twice.");

    Init_default_options();

    for (i = 0; i < option_count; i++)
    {
        if (Option_add_desc(&opts[i]) == false)
            return false;
    }

    options_inited = true;

    return true;
}

void Free_options(void)
{
    int i, option_count = NELEM(opts);

    if (options_inited)
    {
        options_inited = false;
        for (i = 0; i < option_count; i++)
        {
            if (opts[i].type == valString)
            {
                char **str_ptr = (char **)opts[i].variable;
                char *str = *str_ptr;
                if (str != NULL && str != opts[i].defaultValue)
                {
                    free(str);
                    *str_ptr = NULL;
                }
            }
        }
    }
}

option_desc *Find_option_by_name(const char *name)
{
    int j, option_count = NELEM(opts);

    for (j = 0; j < option_count; j++)
    {
        if (!strcasecmp(opts[j].commandLineOption, name) || !strcasecmp(opts[j].name, name))
            return (&opts[j]);
    }
    return NULL;
}

void Timing_setup(void)
{
    LIMIT(FPS, 1, MAX_SERVER_FPS);
    //     LIMIT(options.gameSpeed, 0.0, FPS);
    // #ifndef SELECT_SCHED
    //     LIMIT(options.timerResolution, 0, 100);
    // #endif
    //     if (options.gameSpeed == 0.0)
    //         options.gameSpeed = FPS;
    //     if (options.gameSpeed < FPS / 50.)
    //         options.gameSpeed = FPS / 50.;

    //     /*
    //      * Calculate amount of game time that elapses per frame.
    //      */
    //     timeStep = options.gameSpeed / FPS;

    //     /*
    //      * Calculate amount of real time that elapses per frame.
    //      */
    //     timePerFrame = 1.0 / FPS;

    /*
     * EXPERIMENTAL FEATURE:
     * Negative values for friction give an "acceleration area".
     * kps - maybe we should remove FrictionArea and add AccelerationArea.
     */
    LIMIT(options.frictionSetting, -1.0, 1.0);
    friction = options.frictionSetting;
    if (friction < 1.0)
        friction = 1.0 - pow(1.0 - friction, timeStep);

    /* Adjust friction area friction suitable for gameSpeed */
    {
        int i;

        LIMIT(options.blockFriction, -1.0, 1.0);

        for (i = 0; i < Num_frictionAreas(); i++)
        {
            friction_area_t *fa = FrictionArea_by_index(i);
            double fric;

            /*
             * On xp maps, use blockFriction for all the friction areas,
             * on xp2 maps each friction area has an own friction value.
             */
            if (is_polygon_map)
                fric = fa->friction_setting;
            else
                fric = options.blockFriction;

            LIMIT(fric, -1.0, 1.0);
            if (fric < 1.0)
                fric = 1.0 - pow(1.0 - fric, timeStep);
            fa->friction = fric;
        }
    }

    /* ecm size used to be halved every update on old servers */
    ecmSizeFactor = pow(0.5, timeStep);

    {
        double cor_angle;

        cor_angle = options.coriolis * PI / 180.0;

        coriolisCosine = cos(cor_angle / timeStep);
        coriolisSine = sin(cor_angle / timeStep);
    }

    // #ifdef SELECT_SCHED
    //     install_timer_tick(NULL, FPS);
    // #else
    //     install_timer_tick(NULL, options.timerResolution ? options.timerResolution
    //                                                      : FPS);
    // #endif

    install_timer_tick(nullptr, FPS);
}